name: Nix-based tests

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        OS: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.OS }}
    env:
      RUST_BACKTRACE: True
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: mamba-org/setup-micromamba@v1 
        with:
          environment-file: environment.yml
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test
      - name: Run Python tests
        shell: bash -el {0}
        run: pytest tests/python
