name: Nix-based tests

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        OS: ["ubuntu-latest"]
        PYTHON_VERSION: ['3.8', '3.9', '3.10', '3.11']
        include:
          - OS: macos-latest-xlarge
            PYTHON_VERSION: "3.11"
    runs-on: ${{ matrix.OS }}
    env:
      RUST_BACKTRACE: True
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: mamba-org/setup-micromamba@v1 
        with:
          environment-file: environment.yml
      - name: Run tests
        run: cargo test
      - name: Build
        run: cargo build --all
      - name: Run Python tests
        run: pytest tests/python
