name: Pip based

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Cargo build
      run: cargo build --verbose --all
    - name: Run Rust tests
      run: cargo test --verbose
    - name: Run Python tests
      run: pytest tests/python -s
