name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Run tests
        run: |
          nix develop --command \
          cargo test
      - name: Build release
        run: |
          nix develop --command \
          cargo build --all
      - name: Run Python tests
        run: |
          nix develop --command \
          pytest tests/python
